application: preaton-playground
module: default
version: v1 
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: MySQLdb
  version: "1.2.4"

env_variables:
  LOCAL_SLEEPER_SERVICE_URL: "http://localhost:8081"
  SLEEPER_SERVICE_URL: "https://sleeper.preaton-playground.appspot.com/"
  